//tealium universal tag - utag.28 ut4.0.202103311727, Copyright 2021 Tealium.com Inc. All Rights Reserved.
window._da_=window._da_||[];try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;utag.globals=utag.globals||{};u.ev={"view":1,"link":1};u.initialized=false;u.scriptrequested=false;u.queue=[];u.map={};u.extend=[];u.send=function(utag_event,data_layer){if(u.ev[utag_event]||u.ev.all!==undefined){utag.DB("send:28");utag.DB(data_layer);var a,b,c,d,query_params;a=utag_event;b=data_layer;u.data={"qsp_delim":"&","kvp_delim":"=","base_url":"https://cdn.decibelinsight.net/i/##utag_account##/di.js","da_accountId":"13878","da_propertyId":"490202","di":"decibelInsight","customDimensions":{},"event_queue":[]};utag.DB("send:28:EXTENSIONS");utag.DB(data_layer);query_params=[];for(var mapping_key in utag.loader.GV(u.map)){if(data_layer[mapping_key]!==undefined&&data_layer[mapping_key]!==""){var destinations=u.map[mapping_key].split(",");for(var i=0;i<destinations.length;i++){mapFunc(destinations[i].split("."),u.data,data_layer[mapping_key]);}}else{var event_destinations=mapping_key.split(":");if(event_destinations.length===2&&data_layer[event_destinations[0]]===event_destinations[1]){if(u.map[mapping_key]){u.data.event_queue=u.data.event_queue.concat(u.map[mapping_key].split(","));}}}}
utag.DB("send:28:MAPPINGS");utag.DB(u.data);u.data.customer_id=u.data.customer_id||data_layer._ccustid||"";if(!u.data.da_accountId){utag.DB(u.id+": Tag not fired: Required attribute Account ID not populated");return;}
if(u.initialized){loaderCallback(data_layer);}else{u.initialized=true;window._da_.oldErr=window.onerror;window._da_.err=[];window.onerror=function(){_da_.err.push(arguments);_da_.oldErr&&_da_.oldErr.apply(d,Array.prototype.slice.call(arguments));};window.DecibelInsight=u.data.di;window[u.data.di]=window[u.data.di]||function(){(window[u.data.di].q=window[u.data.di].q||[]).push(arguments);};u.queue.push({"data":u.data,"data_layer":data_layer});if(!u.scriptrequested){u.scriptrequested=true;if(u.data.da_propertyId){u.data.base_url="https://cdn.decibelinsight.net/i/##utag_account##/##utag_property##/di.js";u.data.base_url=u.data.base_url.replace("##utag_property##",u.data.da_propertyId);}
u.data.base_url=u.data.base_url.replace("##utag_account##",u.data.da_accountId);utag.ut.loader({"type":"script","src":u.data.base_url,"cb":callback,"loc":"script","id":"utag_28","attrs":{}});}}
utag.DB("send:28:COMPLETE");}};function loaderCallback(data_layer){utag.DB("send:28:CALLBACK");u.initialized=true;var lookup_id=data_layer.tealium_random;if(typeof lookup_id!=="undefined"){utag.globals[lookup_id]=window.utag.globals[lookup_id]||{};utag.globals[lookup_id]["decibelInsightSessionId"]=decibelInsight("getSessionId");}
var dimension;for(dimension in u.data["customDimensions"]){decibelInsight("sendCustomDimension",dimension,u.data["customDimensions"][dimension]);}
var remember="";for(var i=0;i<u.data.event_queue.length;i++){switch(u.data.event_queue[i]){case"sendApplicationError":if(u.data.errorMessageCssSelector){decibelInsight("sendApplicationError",u.data.errorMessageCssSelector,true);}else{decibelInsight("sendApplicationError",u.data.errorMessage);}
break;case"sendGoal":if(u.data.goalName&&u.data.goalValue){decibelInsight("sendGoal",u.data.goalName,u.data.goalValue);}else if(!u.data.goalName){decibelInsight("sendGoal",u.data.goalName);}
break;case"sendHTTPError":decibelInsight("sendHTTPError",parseInt(u.data.httpErrorCode));break;case"setCollection":remember=isNaN(parseInt(u.data.collectionRemember))?toBoolean(u.data.collectionRemember):parseInt(u.data.collectionRemember);decibelInsight("setCollection",u.data.collectionStatus,u.data.remember);break;case"setRetention":remember=isNaN(parseInt(u.data.retentionRemember))?toBoolean(u.data.retentionRemember):parseInt(u.data.retentionRemember);decibelInsight("setRetention",u.data.retentionStatus,remember);break;case"setPageRole":decibelInsight.setPageRole(u.data.pageRole);break;case"trackPageView":decibelInsight("trackPageView",u.data.pageName,u.data.pageViewParams);break;case"updateUserId":decibelInsight("updateUserId",u.data.customer_id);break;default:break;}}
utag.DB("send:28:CALLBACK:COMPLETE");}
function toBoolean(val){val=val||"";return val===true||val.toLowerCase()==="true"||val.toLowerCase()==="on";}
function mapFunc(arr,obj,item){var i=arr.shift();obj[i]=obj[i]||{};if(arr.length>0){mapFunc(arr,obj[i],item);}else{obj[i]=item;}}
function callback(){var data={};while(data=u.queue.shift()){u.data=data.data;loaderCallback(data.data_layer);}}
utag.o[loader].loader.LOAD(id);}("28","intuit.cg-mint"));}catch(error){utag.DB(error);}
