//tealium universal tag - utag.51 ut4.0.202212051444, Copyright 2022 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
u.encode=function(a,b){b="";try{b=encodeURIComponent(a)}catch(e){utag.DB(e);}if(b==""){b=escape(a);}return b}
u.ev={"view":1};u.scriptrequested=false;u.rp=function(a,b){if(typeof a!=="undefined"&&a.indexOf("@@")>0){a=a.replace(/@@([^@]+)@@/g,function(m,d){if(b[d]){return u.encode(b[d]);}else{return"";}});}
return a;};u.map={"_sm_51_1":"gdpr_util","_sm_51_2":"consent_widget"};u.extend=[function(a,b){try{b['_sm_51_1']="https://uxfabric.intuitcdn.net/gdpr-util/2.6.0/gdprUtilBundle.js";}catch(e){utag.DB(e);}
try{b['_sm_51_2']="https://uxfabric.intuitcdn.net/gdpr-widget/2.5.21/ccpa-widget-en.js";}catch(e){utag.DB(e);}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f;u.data={"gdpr_util":"https://uxfabric.intuitcdn.net/gdpr-util/2.5.0/gdprUtilBundle.js","consent_widget":"https://uxfabric.intuitcdn.net/gdpr-widget/2.5.2/ccpa-widget-en.js","tag_type":"script","attribute":{}};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};utag.DB("send:51:EXTENSIONS");utag.DB(b);c=[];for(d in utag.loader.GV(u.map)){if(typeof b[d]!=="undefined"&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(e[f].indexOf("attribute.")===0){u.data.attribute[e[f].split(".")[1]]=b[d];}else if(!u.data.hasOwnProperty(e[f])){c.push(e[f]+"##kvp_delim##"+u.encode(b[d]));}
u.data[e[f]]=b[d];}}}
u.callback=u.callback||function(){u.loader({"type":u.data.tag_type,"src":u.data.consent_widget,"loc":"script","id":"utag_51_consent","cb":function(){},"attrs":u.data.attribute});};if(!u.scriptrequested){u.scriptrequested=true;u.loader({"type":u.data.tag_type,"src":u.data.gdpr_util,"loc":"script","id":"utag_51_gdprutil","cb":u.callback,"attrs":u.data.attribute});}
utag.DB("send:51:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("51","intuit.cg-mint"));}catch(error){utag.DB(error);}
